/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weekly Report */
        get: operations["get_weekly_report_api_v1_weekly_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring Config */
        get: operations["get_scoring_config_api_v1_config_scoring_get"];
        /** Put Scoring Config */
        put: operations["put_scoring_config_api_v1_config_scoring_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Leads */
        get: operations["export_leads_api_v1_leads_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Detail */
        get: operations["get_lead_detail_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Lead Status */
        patch: operations["update_lead_status_api_v1_leads__lead_id__status_patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Follow Ups */
        get: operations["list_follow_ups_api_v1_leads__lead_id__follow_ups_get"];
        put?: never;
        /** Create Follow Up */
        post: operations["create_follow_up_api_v1_leads__lead_id__follow_ups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/follow-ups/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Due Follow Ups */
        get: operations["list_due_follow_ups_api_v1_follow_ups_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawl/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Crawl */
        post: operations["trigger_crawl_api_v1_crawl_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Pipeline */
        post: operations["run_pipeline_api_v1_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Score */
        get: operations["demo_score_api_v1_demo_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo-call-script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Call Script */
        post: operations["demo_call_script_api_v1_demo_call_script_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CallScript */
        CallScript: {
            /** Opening */
            opening: string;
            /** Questions */
            questions: string[];
            /** Wechat Follow Up */
            wechat_follow_up: string;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Keyword Groups */
            keyword_groups: components["schemas"]["KeywordGroup"][];
            /** Scoring Dimensions */
            scoring_dimensions: components["schemas"]["ScoringDimension"][];
            /** Product Packages */
            product_packages: components["schemas"]["ProductPackage"][];
        };
        /** CrawlRequest */
        CrawlRequest: {
            /** Query */
            query: string;
            /**
             * Source
             * @default ccgp
             */
            source: string;
        };
        /** DistributionItem */
        DistributionItem: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id?: string | null;
            /** Url */
            url: string;
            /** Title */
            title?: string | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Parse Status */
            parse_status: string;
            /** Document Type */
            document_type?: string | null;
        };
        /** DueFollowUp */
        DueFollowUp: {
            /**
             * Follow Up Id
             * Format: uuid
             */
            follow_up_id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /** Organization Name */
            organization_name?: string | null;
            /**
             * Next Action At
             * Format: date-time
             */
            next_action_at: string;
            /** Result */
            result: string;
        };
        /** EnumItem */
        EnumItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** FollowUpCreate */
        FollowUpCreate: {
            /** Channel */
            channel: string;
            /** Result */
            result: string;
            /** Notes */
            notes?: string | null;
            /** Contact Id */
            contact_id?: string | null;
        };
        /** FollowUpOut */
        FollowUpOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Channel */
            channel: string;
            /** Result */
            result: string;
            /** Notes */
            notes?: string | null;
            /** Next Action At */
            next_action_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GradeThresholds */
        GradeThresholds: {
            /** S */
            S: number;
            /** A */
            A: number;
            /** B */
            B: number;
            /** C */
            C: number;
            /**
             * D
             * @default 0
             */
            D: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeywordGroup */
        KeywordGroup: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Keywords */
            keywords: string[];
        };
        /** LeadDetail */
        LeadDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            organization: components["schemas"]["OrganizationBrief"];
            signal: components["schemas"]["SignalBrief"];
            score: components["schemas"]["ScoreBrief"];
            call_script: components["schemas"]["CallScript"];
            /** Customer Type */
            customer_type?: string | null;
            /** Recommended Package */
            recommended_package?: string | null;
            /** Budget Bucket */
            budget_bucket?: string | null;
            /** Lead Status */
            lead_status: string;
            /** Owner */
            owner?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LeadListItem */
        LeadListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Organization Name */
            organization_name?: string | null;
            /** Customer Type */
            customer_type?: string | null;
            /** Recommended Package */
            recommended_package?: string | null;
            /** Budget Bucket */
            budget_bucket?: string | null;
            /** Signal Type */
            signal_type?: string | null;
            /** Province */
            province?: string | null;
            /** Lead Status */
            lead_status: string;
            /** Total Score */
            total_score: number;
            /** Grade */
            grade: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Signal Types */
            signal_types: components["schemas"]["EnumItem"][];
            /** Statuses */
            statuses: components["schemas"]["EnumItem"][];
            /** Grades */
            grades: string[];
            /** Budget Buckets */
            budget_buckets: string[];
        };
        /** OrganizationBrief */
        OrganizationBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** City */
            city?: string | null;
            /** County */
            county?: string | null;
            /** Organization Type */
            organization_type?: string | null;
        };
        /** PipelineRequest */
        PipelineRequest: {
            /** Query */
            query: string;
            /**
             * Source
             * @default ccgp
             */
            source: string;
        };
        /** ProductPackage */
        ProductPackage: {
            /** Name */
            name: string;
            /** Target */
            target: string;
            /** Desc */
            desc: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ScoreBrief */
        ScoreBrief: {
            /** Total Score */
            total_score: number;
            /** Grade */
            grade: string;
            /**
             * Budget Strength Score
             * @default 0
             */
            budget_strength_score: number;
            /**
             * Scenario Fit Score
             * @default 0
             */
            scenario_fit_score: number;
            /**
             * Timing Score
             * @default 0
             */
            timing_score: number;
            /**
             * Reachability Score
             * @default 0
             */
            reachability_score: number;
            /**
             * Leverage Score
             * @default 0
             */
            leverage_score: number;
        };
        /** ScoringDimension */
        ScoringDimension: {
            /** Name */
            name: string;
            /** Max Score */
            max_score: number;
            /** Description */
            description: string;
        };
        /** ScoringRulesUpdate */
        ScoringRulesUpdate: {
            /**
             * Version
             * @default 0.1
             */
            version: string;
            /** Max Scores */
            max_scores: {
                [key: string]: number;
            };
            grades: components["schemas"]["GradeThresholds"];
            /** Budget Strength */
            budget_strength: {
                [key: string]: number;
            };
            /** Scenario Fit */
            scenario_fit: {
                [key: string]: number;
            };
            /** Timing */
            timing: {
                [key: string]: number;
            };
            /** Reachability */
            reachability: {
                [key: string]: number;
            };
            /** Leverage */
            leverage: {
                [key: string]: number;
            };
        };
        /** SignalBrief */
        SignalBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Signal Type */
            signal_type: string;
            /** Title */
            title?: string | null;
            /** Budget Amount */
            budget_amount?: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Evidence Text */
            evidence_text?: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /** Base Url */
            base_url?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Rate Limit Per Minute
             * @default 20
             */
            rate_limit_per_minute: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Total */
            total: number;
            /** Sa Count */
            sa_count: number;
            /** Pending */
            pending: number;
            /** Scheduled */
            scheduled: number;
            /** Invalid */
            invalid: number;
            /** Invalid Rate */
            invalid_rate: string;
            /** Signal Type Distribution */
            signal_type_distribution: components["schemas"]["DistributionItem"][];
            /** Package Distribution */
            package_distribution: components["schemas"]["DistributionItem"][];
            /** Province Distribution */
            province_distribution: components["schemas"]["DistributionItem"][];
        };
        /** StatusUpdate */
        StatusUpdate: {
            /** Status */
            status: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
            /** Display Name */
            display_name: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyReport */
        WeeklyReport: {
            /** New Leads */
            new_leads: number;
            /** Followed Up */
            followed_up: number;
            /** Contacted */
            contacted: number;
            /** Scheduled */
            scheduled: number;
            /** Won */
            won: number;
            /** Lost */
            lost: number;
            /** Conversion Rate */
            conversion_rate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    get_weekly_report_api_v1_weekly_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    get_scoring_config_api_v1_config_scoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_scoring_config_api_v1_config_scoring_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringRulesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                grade?: string | null;
                status?: string | null;
                signal_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_leads_api_v1_leads_export_get: {
        parameters: {
            query: {
                format: "csv" | "xlsx";
                grade?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_detail_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_status_api_v1_leads__lead_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_follow_ups_api_v1_leads__lead_id__follow_ups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_follow_up_api_v1_leads__lead_id__follow_ups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUpOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_due_follow_ups_api_v1_follow_ups_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueFollowUp"][];
                };
            };
        };
    };
    trigger_crawl_api_v1_crawl_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_api_v1_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_auth_me_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    demo_score_api_v1_demo_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demo_call_script_api_v1_demo_call_script_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
